// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-jkSoUVUOY-ngrmI70L21rYQBfYaNdts',
    appId: '1:231730406983:web:8c6c1aafafe4334f817362',
    messagingSenderId: '231730406983',
    projectId: 'iit-ropar-ismp-app',
    authDomain: 'iit-ropar-ismp-app.firebaseapp.com',
    storageBucket: 'iit-ropar-ismp-app.firebasestorage.app',
    measurementId: 'G-D4Q4WKJW9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcoMqURpYa8DQaAfbGFhXv7140ItEcGFE',
    appId: '1:231730406983:android:244e9e51786108bb817362',
    messagingSenderId: '231730406983',
    projectId: 'iit-ropar-ismp-app',
    storageBucket: 'iit-ropar-ismp-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEtOOBzkOrZXn16Qq3TZFFKxS9gdd-FnM',
    appId: '1:231730406983:ios:2bf571bd7d2aa5ff817362',
    messagingSenderId: '231730406983',
    projectId: 'iit-ropar-ismp-app',
    storageBucket: 'iit-ropar-ismp-app.firebasestorage.app',
    iosBundleId: 'ismp.iitropar.ismpApp',
  );
}
